/// Golden tests for ``HostISTFT.swift``'s ``hostISTFTInverse`` against
/// ``kokoro/custom_stft.py`` ``CustomSTFT.inverse``.
///
/// Fixtures are generated by ``scripts/dump_istft_golden.py`` (see that
/// file's docstring) into
/// ``Fixtures/istft_golden/{synthetic,real_3s}_{spec,phase,waveform}.f32`` —
/// flat little-endian float32, no header. Shapes are fixed constants,
/// mirrored here from the dump script's own printed output.

import Accelerate
import XCTest
@testable import KokoroPipeline

final class HostISTFTTests: XCTestCase {

    private func loadFloatArray(_ resource: String) throws -> [Float] {
        guard let url = Bundle.module.url(
            forResource: resource,
            withExtension: "f32",
            subdirectory: "Fixtures/istft_golden"
        ) else {
            throw XCTSkip("Missing fixture \(resource).f32 — run scripts/dump_istft_golden.py")
        }
        let data = try Data(contentsOf: url)
        precondition(data.count % MemoryLayout<Float>.size == 0, "\(resource).f32 is not float32-aligned")
        return data.withUnsafeBytes { Array($0.bindMemory(to: Float.self)) }
    }

    private func maxAbsDifference(_ a: [Float], _ b: [Float]) -> Float {
        precondition(a.count == b.count)
        var diff = [Float](repeating: 0, count: a.count)
        vDSP_vsub(b, 1, a, 1, &diff, 1, vDSP_Length(a.count))
        var maxAbs: Float = 0
        vDSP_maxmgv(diff, 1, &maxAbs, vDSP_Length(a.count))
        return maxAbs
    }

    /// Fixed-seed random (non-network) magnitude/phase — the inverse must
    /// hold for any spec/phase pair the network could produce, matching
    /// ``tests/test_custom_stft.py``'s inconsistent-spectrogram coverage.
    func testSyntheticGolden() throws {
        let frameCount = 40
        let spec = try loadFloatArray("synthetic_spec")
        let phase = try loadFloatArray("synthetic_phase")
        let expected = try loadFloatArray("synthetic_waveform")

        XCTAssertEqual(spec.count, HarmonicConstants.stftFreqBins * frameCount)
        XCTAssertEqual(phase.count, HarmonicConstants.stftFreqBins * frameCount)

        let waveform = hostISTFTInverse(spec: spec, phase: phase, frameCount: frameCount)

        XCTAssertEqual(waveform.count, expected.count)
        let maxAbs = maxAbsDifference(waveform, expected)
        XCTAssertLessThan(maxAbs, 1e-4, "synthetic case max-abs error \(maxAbs) exceeds golden tolerance")
    }

    /// Real spec/phase captured from the actual ``GeneratorFromHar`` body at
    /// the shipped 3s decoder-har-post geometry (T1's checkpoint baseline —
    /// see ``README/Plans/ane-generator-a14-v1.md``). 240 ASR frames, 14,401
    /// iSTFT frames, 72,000-sample waveform.
    func testReal3sBucketGolden() throws {
        let frameCount = 14401
        let spec = try loadFloatArray("real_3s_spec")
        let phase = try loadFloatArray("real_3s_phase")
        let expected = try loadFloatArray("real_3s_waveform")

        XCTAssertEqual(spec.count, HarmonicConstants.stftFreqBins * frameCount)
        XCTAssertEqual(phase.count, HarmonicConstants.stftFreqBins * frameCount)
        XCTAssertEqual(expected.count, 72_000)

        let waveform = hostISTFTInverse(spec: spec, phase: phase, frameCount: frameCount)

        XCTAssertEqual(waveform.count, expected.count)
        let maxAbs = maxAbsDifference(waveform, expected)
        XCTAssertLessThan(maxAbs, 1e-4, "real 3s-bucket case max-abs error \(maxAbs) exceeds golden tolerance")
    }
}
